package com.eivo.roleplayai;

import android.app.Activity;
import android.app.AlertDialog;
import android.graphics.BitmapFactory;
import android.graphics.Color;
import android.graphics.Typeface;
import android.graphics.drawable.GradientDrawable;
import android.os.Bundle;
import android.text.InputType;
import android.view.Gravity;
import android.view.View;
import android.view.ViewGroup;
import android.view.Window;
import android.widget.Button;
import android.widget.CheckBox;
import android.widget.EditText;
import android.widget.ImageView;
import android.widget.LinearLayout;
import android.widget.ScrollView;
import android.widget.Space;
import android.widget.TextView;
import android.widget.Toast;

import java.io.File;
import java.io.FileOutputStream;
import java.util.ArrayList;
import java.util.List;
import java.util.concurrent.ExecutorService;
import java.util.concurrent.Executors;

public class MainActivity extends Activity {
    private static final int BG = Color.rgb(9, 9, 11), PANEL = Color.rgb(24, 24, 27), PANEL_2 = Color.rgb(39, 39, 42), TEXT = Color.rgb(244, 244, 245), MUTED = Color.rgb(161, 161, 170), ACCENT = Color.rgb(167, 139, 250), USER_BUBBLE = Color.rgb(76, 29, 149);
    private Store store; private CryptoStore cryptoStore; private final ExecutorService executor = Executors.newSingleThreadExecutor();
    private CharacterProfile activeCharacter; private List<ChatMessage> activeMessages = new ArrayList<>(); private LinearLayout chatMessagesContainer; private ScrollView chatScroll; private EditText chatInput; private Button sendButton; private Button imageButton; private String screen = "home";

    @Override protected void onCreate(Bundle savedInstanceState) { super.onCreate(savedInstanceState); Window w=getWindow(); w.setStatusBarColor(BG); w.setNavigationBarColor(BG); store=new Store(this); cryptoStore=new CryptoStore(this); if(!store.isAdultConfirmed()) showAgeGate(); else showHome(); }
    @Override protected void onDestroy(){ executor.shutdownNow(); super.onDestroy(); }
    @Override public void onBackPressed(){ if("home".equals(screen)||"age".equals(screen)) super.onBackPressed(); else showHome(); }

    private void showAgeGate(){ screen="age"; LinearLayout root=rootColumn(28); root.setGravity(Gravity.CENTER_VERTICAL); TextView badge=text("18+ ONLY",13,ACCENT,true); badge.setGravity(Gravity.CENTER); badge.setBackground(roundBg(Color.rgb(46,16,101),999)); badge.setPadding(dp(14),dp(8),dp(14),dp(8)); root.addView(badge,wrap()); root.addView(space(18)); root.addView(text("Roleplay AI",34,TEXT,true),matchWrap()); root.addView(space(10)); root.addView(text("Private AI roleplay with custom adult characters, persistent chats and scene images.",17,MUTED,false),matchWrap()); root.addView(space(24)); CheckBox confirm=new CheckBox(this); confirm.setText("I confirm that I am 18 years or older."); confirm.setTextColor(TEXT); confirm.setTextSize(16); root.addView(confirm,matchWrap()); root.addView(space(16)); Button enter=primaryButton("Enter"); enter.setOnClickListener(v->{ if(!confirm.isChecked()){toast("You must confirm that you are 18+.");return;} store.setAdultConfirmed(true);showHome();}); root.addView(enter,matchHeight(54)); root.addView(space(12)); root.addView(text("All characters and romantic/mature roleplay must involve adults. Provider safety rules still apply.",13,MUTED,false),matchWrap()); setContentView(root); }

    private void showHome(){ screen="home"; activeCharacter=null; LinearLayout outer=rootColumn(0); LinearLayout header=horizontal(dp(18),dp(18)); header.setGravity(Gravity.CENTER_VERTICAL); LinearLayout titles=new LinearLayout(this); titles.setOrientation(LinearLayout.VERTICAL); titles.addView(text("Roleplay AI",28,TEXT,true)); titles.addView(text("Choose a character",14,MUTED,false)); header.addView(titles,new LinearLayout.LayoutParams(0,ViewGroup.LayoutParams.WRAP_CONTENT,1)); Button settings=smallButton("Settings"); settings.setOnClickListener(v->showSettings()); header.addView(settings); header.addView(spaceHorizontal(8)); Button add=smallButton("+ Character"); add.setOnClickListener(v->showCreateCharacter()); header.addView(add); outer.addView(header,matchWrap()); ScrollView scroll=new ScrollView(this); LinearLayout list=new LinearLayout(this); list.setOrientation(LinearLayout.VERTICAL); list.setPadding(dp(18),dp(8),dp(18),dp(24)); for(CharacterProfile c:store.getCharacters()) list.addView(characterCard(c)); scroll.addView(list,matchWrap()); outer.addView(scroll,new LinearLayout.LayoutParams(ViewGroup.LayoutParams.MATCH_PARENT,0,1)); setContentView(outer); }

    private View characterCard(CharacterProfile c){ LinearLayout card=new LinearLayout(this); card.setOrientation(LinearLayout.VERTICAL); card.setPadding(dp(18),dp(18),dp(18),dp(16)); card.setBackground(roundBg(PANEL,20)); LinearLayout.LayoutParams cp=matchWrap(); cp.setMargins(0,dp(8),0,dp(8)); card.setLayoutParams(cp); card.addView(text(c.name,22,TEXT,true)); card.addView(space(7)); String persona=c.persona==null?"":c.persona; if(persona.length()>180) persona=persona.substring(0,180)+"…"; card.addView(text(persona,14,MUTED,false),matchWrap()); card.addView(space(14)); LinearLayout actions=horizontal(0,0); Button chat=primaryButton("Chat"); chat.setOnClickListener(v->openChat(c)); actions.addView(chat,new LinearLayout.LayoutParams(0,dp(48),1)); actions.addView(spaceHorizontal(8)); Button delete=smallButton("Delete"); delete.setOnClickListener(v->confirmDelete(c)); actions.addView(delete,new LinearLayout.LayoutParams(dp(92),dp(48))); card.addView(actions,matchWrap()); card.setOnClickListener(v->openChat(c)); return card; }
    private void confirmDelete(CharacterProfile c){ new AlertDialog.Builder(this).setTitle("Delete "+c.name+"?").setMessage("This will also delete this character's chat history.").setNegativeButton("Cancel",null).setPositiveButton("Delete",(d,w)->{store.deleteCharacter(c.id);showHome();}).show(); }

    private void showCreateCharacter(){ screen="create"; LinearLayout root=formScreen("New character","Build the persona the model should stay consistent with."); EditText name=field("Name",false,false), persona=field("Persona, personality, appearance, speaking style, boundaries…",true,false), greeting=field("First message / greeting",true,false); root.addView(label("Name"));root.addView(name,matchHeight(54));root.addView(space(14));root.addView(label("Persona"));root.addView(persona,matchHeight(150));root.addView(space(14));root.addView(label("Greeting"));root.addView(greeting,matchHeight(110));root.addView(space(20)); Button save=primaryButton("Create character"); save.setOnClickListener(v->{String n=name.getText().toString().trim(),p=persona.getText().toString().trim(),g=greeting.getText().toString().trim(); if(n.isEmpty()||p.isEmpty()){toast("Name and persona are required.");return;} if(g.isEmpty())g="Hey. I'm "+n+"."; store.addCharacter(n,p,g);showHome();}); root.addView(save,matchHeight(54)); setContentView(wrapForm(root)); }

    private void showSettings(){ screen="settings"; LinearLayout root=formScreen("Settings","Bring your own OpenRouter key for this personal-testing build."); EditText apiKey=field("sk-or-v1-…",false,true);apiKey.setText(cryptoStore.getApiKey()); EditText chatModel=field("openrouter/free",false,false);chatModel.setText(store.getChatModel()); EditText imageModel=field("google/gemini-2.5-flash-image",false,false);imageModel.setText(store.getImageModel()); root.addView(label("OpenRouter API key"));root.addView(apiKey,matchHeight(54));root.addView(space(14));root.addView(label("Chat model"));root.addView(chatModel,matchHeight(54));root.addView(space(14));root.addView(label("Image model"));root.addView(imageModel,matchHeight(54));root.addView(space(10));root.addView(text("The key is encrypted before local storage using Android Keystore. Provider usage may cost money. A public release should move this key behind a backend proxy.",13,MUTED,false),matchWrap());root.addView(space(20)); Button save=primaryButton("Save settings"); save.setOnClickListener(v->{String cm=chatModel.getText().toString().trim(),im=imageModel.getText().toString().trim();if(cm.isEmpty()||im.isEmpty()){toast("Model names cannot be empty.");return;}try{cryptoStore.saveApiKey(apiKey.getText().toString());store.setChatModel(cm);store.setImageModel(im);toast("Saved.");showHome();}catch(Exception e){toast("Could not secure API key: "+e.getMessage());}});root.addView(save,matchHeight(54));setContentView(wrapForm(root)); }

    private void openChat(CharacterProfile character){ screen="chat";activeCharacter=character;activeMessages=store.getMessages(character);LinearLayout root=rootColumn(0),top=horizontal(dp(12),dp(10));top.setGravity(Gravity.CENTER_VERTICAL);Button back=smallButton("←");back.setOnClickListener(v->showHome());top.addView(back,new LinearLayout.LayoutParams(dp(52),dp(44)));top.addView(spaceHorizontal(10));LinearLayout titleCol=new LinearLayout(this);titleCol.setOrientation(LinearLayout.VERTICAL);titleCol.addView(text(character.name,20,TEXT,true));titleCol.addView(text("AI character • adult-only",12,MUTED,false));top.addView(titleCol,new LinearLayout.LayoutParams(0,ViewGroup.LayoutParams.WRAP_CONTENT,1));Button clear=smallButton("Clear");clear.setOnClickListener(v->{store.clearMessages(character);activeMessages=store.getMessages(character);renderMessages();});top.addView(clear);root.addView(top,matchWrap()); chatScroll=new ScrollView(this);chatMessagesContainer=new LinearLayout(this);chatMessagesContainer.setOrientation(LinearLayout.VERTICAL);chatMessagesContainer.setPadding(dp(14),dp(10),dp(14),dp(10));chatScroll.addView(chatMessagesContainer,matchWrap());root.addView(chatScroll,new LinearLayout.LayoutParams(ViewGroup.LayoutParams.MATCH_PARENT,0,1));LinearLayout composer=horizontal(dp(10),dp(10));composer.setGravity(Gravity.BOTTOM);imageButton=smallButton("Image");imageButton.setOnClickListener(v->generateSceneImage());composer.addView(imageButton,new LinearLayout.LayoutParams(dp(76),dp(52)));composer.addView(spaceHorizontal(8));chatInput=field("Message "+character.name+"…",true,false);chatInput.setMaxLines(5);composer.addView(chatInput,new LinearLayout.LayoutParams(0,dp(52),1));composer.addView(spaceHorizontal(8));sendButton=primaryButton("Send");sendButton.setOnClickListener(v->sendCurrentMessage());composer.addView(sendButton,new LinearLayout.LayoutParams(dp(82),dp(52)));root.addView(composer,matchWrap());setContentView(root);renderMessages(); }

    private void renderMessages(){if(chatMessagesContainer==null||activeCharacter==null)return;chatMessagesContainer.removeAllViews();for(ChatMessage m:activeMessages){if(m.imagePath!=null)addImageBubble(m);else addTextBubble(m);}scrollChatBottom();}
    private void addTextBubble(ChatMessage m){boolean user="user".equals(m.role);LinearLayout row=new LinearLayout(this);row.setGravity(user?Gravity.RIGHT:Gravity.LEFT);TextView bubble=text(m.content,16,TEXT,false);bubble.setPadding(dp(14),dp(11),dp(14),dp(11));bubble.setBackground(roundBg(user?USER_BUBBLE:PANEL_2,18));LinearLayout.LayoutParams bp=new LinearLayout.LayoutParams(ViewGroup.LayoutParams.WRAP_CONTENT,ViewGroup.LayoutParams.WRAP_CONTENT);bp.setMargins(user?dp(48):0,dp(5),user?0:dp(48),dp(5));row.addView(bubble,bp);chatMessagesContainer.addView(row,matchWrap());}
    private void addImageBubble(ChatMessage m){File f=new File(m.imagePath);if(!f.exists())return;ImageView image=new ImageView(this);image.setImageBitmap(BitmapFactory.decodeFile(f.getAbsolutePath()));image.setAdjustViewBounds(true);image.setScaleType(ImageView.ScaleType.CENTER_CROP);image.setBackground(roundBg(PANEL_2,18));image.setPadding(dp(3),dp(3),dp(3),dp(3));LinearLayout.LayoutParams p=new LinearLayout.LayoutParams(ViewGroup.LayoutParams.MATCH_PARENT,ViewGroup.LayoutParams.WRAP_CONTENT);p.setMargins(0,dp(8),dp(46),dp(8));chatMessagesContainer.addView(image,p);}

    private void sendCurrentMessage(){if(activeCharacter==null)return;String message=chatInput.getText().toString().trim();if(message.isEmpty())return;String key=cryptoStore.getApiKey();if(key.isEmpty()){toast("Add your OpenRouter API key in Settings first.");return;}activeMessages.add(ChatMessage.text("user",message));store.saveMessages(activeCharacter.id,activeMessages);chatInput.setText("");renderMessages();setBusy(true,"Thinking…");CharacterProfile character=activeCharacter;List<ChatMessage> snapshot=new ArrayList<>(activeMessages);String model=store.getChatModel();executor.execute(()->{try{String reply=OpenRouterClient.chat(key,model,character,snapshot);runOnUiThread(()->{if(activeCharacter==null||!activeCharacter.id.equals(character.id))return;activeMessages.add(ChatMessage.text("assistant",reply));store.saveMessages(character.id,activeMessages);renderMessages();setBusy(false,null);});}catch(Exception e){runOnUiThread(()->{setBusy(false,null);showError("Chat request failed",e.getMessage());});}});}
    private void generateSceneImage(){if(activeCharacter==null)return;String key=cryptoStore.getApiKey();if(key.isEmpty()){toast("Add your OpenRouter API key in Settings first.");return;}setBusy(true,"Creating image…");CharacterProfile character=activeCharacter;List<ChatMessage> snapshot=new ArrayList<>(activeMessages);String model=store.getImageModel();executor.execute(()->{try{byte[] imageBytes=OpenRouterClient.generateImage(key,model,character,snapshot);File out=new File(getFilesDir(),"scene_"+character.id+"_"+System.currentTimeMillis()+".png");try(FileOutputStream fos=new FileOutputStream(out)){fos.write(imageBytes);}runOnUiThread(()->{if(activeCharacter==null||!activeCharacter.id.equals(character.id))return;activeMessages.add(ChatMessage.image("assistant",out.getAbsolutePath()));store.saveMessages(character.id,activeMessages);renderMessages();setBusy(false,null);});}catch(Exception e){runOnUiThread(()->{setBusy(false,null);showError("Image request failed",e.getMessage());});}});}
    private void setBusy(boolean busy,String label){if(sendButton!=null){sendButton.setEnabled(!busy);sendButton.setText(busy&&label!=null?label:"Send");}if(imageButton!=null)imageButton.setEnabled(!busy);if(chatInput!=null)chatInput.setEnabled(!busy);} private void showError(String title,String message){new AlertDialog.Builder(this).setTitle(title).setMessage(message==null?"Unknown error":message).setPositiveButton("OK",null).show();} private void scrollChatBottom(){if(chatScroll!=null)chatScroll.post(()->chatScroll.fullScroll(View.FOCUS_DOWN));}

    private LinearLayout formScreen(String title,String subtitle){LinearLayout root=new LinearLayout(this);root.setOrientation(LinearLayout.VERTICAL);root.setPadding(dp(20),dp(18),dp(20),dp(28));root.setBackgroundColor(BG);LinearLayout top=horizontal(0,0);top.setGravity(Gravity.CENTER_VERTICAL);Button back=smallButton("← Back");back.setOnClickListener(v->showHome());top.addView(back);root.addView(top,matchWrap());root.addView(space(22));root.addView(text(title,30,TEXT,true),matchWrap());root.addView(space(6));root.addView(text(subtitle,14,MUTED,false),matchWrap());root.addView(space(22));return root;}
    private View wrapForm(LinearLayout form){ScrollView scroll=new ScrollView(this);scroll.setBackgroundColor(BG);scroll.addView(form,matchWrap());return scroll;} private LinearLayout rootColumn(int paddingDp){LinearLayout root=new LinearLayout(this);root.setOrientation(LinearLayout.VERTICAL);root.setPadding(dp(paddingDp),dp(paddingDp),dp(paddingDp),dp(paddingDp));root.setBackgroundColor(BG);return root;} private LinearLayout horizontal(int px,int py){LinearLayout row=new LinearLayout(this);row.setOrientation(LinearLayout.HORIZONTAL);row.setPadding(px,py,px,py);row.setBackgroundColor(BG);return row;}
    private TextView text(String value,int sp,int color,boolean bold){TextView tv=new TextView(this);tv.setText(value);tv.setTextSize(sp);tv.setTextColor(color);if(bold)tv.setTypeface(Typeface.DEFAULT,Typeface.BOLD);tv.setLineSpacing(0,1.08f);return tv;} private TextView label(String value){TextView tv=text(value,13,MUTED,true);tv.setPadding(0,0,0,dp(7));return tv;} private EditText field(String hint,boolean multiline,boolean password){EditText e=new EditText(this);e.setHint(hint);e.setHintTextColor(Color.rgb(113,113,122));e.setTextColor(TEXT);e.setTextSize(15);e.setPadding(dp(14),dp(10),dp(14),dp(10));e.setBackground(roundStrokeBg(PANEL,Color.rgb(63,63,70),14));e.setSingleLine(!multiline);e.setGravity(multiline?Gravity.TOP:Gravity.CENTER_VERTICAL);if(password)e.setInputType(InputType.TYPE_CLASS_TEXT|InputType.TYPE_TEXT_VARIATION_PASSWORD);else if(multiline)e.setInputType(InputType.TYPE_CLASS_TEXT|InputType.TYPE_TEXT_FLAG_MULTI_LINE|InputType.TYPE_TEXT_FLAG_CAP_SENTENCES);else e.setInputType(InputType.TYPE_CLASS_TEXT|InputType.TYPE_TEXT_FLAG_CAP_SENTENCES);return e;}
    private Button primaryButton(String value){Button b=new Button(this);b.setText(value);b.setTextColor(Color.rgb(17,17,20));b.setTextSize(14);b.setAllCaps(false);b.setTypeface(Typeface.DEFAULT,Typeface.BOLD);b.setBackground(roundBg(ACCENT,14));return b;} private Button smallButton(String value){Button b=new Button(this);b.setText(value);b.setTextColor(TEXT);b.setTextSize(13);b.setAllCaps(false);b.setBackground(roundStrokeBg(PANEL,Color.rgb(63,63,70),13));return b;}
    private GradientDrawable roundBg(int color,int radiusDp){GradientDrawable d=new GradientDrawable();d.setColor(color);d.setCornerRadius(dp(radiusDp));return d;} private GradientDrawable roundStrokeBg(int color,int stroke,int radiusDp){GradientDrawable d=roundBg(color,radiusDp);d.setStroke(dp(1),stroke);return d;} private int dp(int value){return Math.round(value*getResources().getDisplayMetrics().density);} private Space space(int height){Space s=new Space(this);s.setLayoutParams(new LinearLayout.LayoutParams(1,dp(height)));return s;} private Space spaceHorizontal(int width){Space s=new Space(this);s.setLayoutParams(new LinearLayout.LayoutParams(dp(width),1));return s;} private LinearLayout.LayoutParams matchWrap(){return new LinearLayout.LayoutParams(ViewGroup.LayoutParams.MATCH_PARENT,ViewGroup.LayoutParams.WRAP_CONTENT);} private LinearLayout.LayoutParams wrap(){return new LinearLayout.LayoutParams(ViewGroup.LayoutParams.WRAP_CONTENT,ViewGroup.LayoutParams.WRAP_CONTENT);} private LinearLayout.LayoutParams matchHeight(int dpHeight){return new LinearLayout.LayoutParams(ViewGroup.LayoutParams.MATCH_PARENT,dp(dpHeight));} private void toast(String message){Toast.makeText(this,message,Toast.LENGTH_SHORT).show();}
}
